### ISSUE TITLE
Permissions issues and more

### ISSUE THREAD

**Issue by treyus30** [pedroanisio/gpu-passthrough-setup#2]
I had to chmod 777 my full "/gpu-passthrough-setup/" dir to get past the following:

`Traceback (most recent call last):
  File "/root/gpu-passthrough-setup/main.py", line 6, in <module>
    from src.system_configurator import SystemConfigurator
  File "/root/gpu-passthrough-setup/src/system_configurator.py", line 4, in <module>
    from src.command_executor import CommandExecutor
  File "/root/gpu-passthrough-setup/src/command_executor.py", line 2, in <module>
    from src.logger import logger
  File "/root/gpu-passthrough-setup/src/logger.py", line 25, in <module>
    logger = setup_logger()
             ^^^^^^^^^^^^^^
  File "/root/gpu-passthrough-setup/src/logger.py", line 13, in setup_logger
    fh = logging.FileHandler('logs/gpu_passthrough.log')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/logs/gpu_passthrough.log'
`

Now I get this:

`2024-08-10 11:55:21,822 - INFO - Checking preconditions...
2024-08-10 11:55:21,822 - INFO - Running precondition check: Check if script is run as root
2024-08-10 11:55:21,827 - INFO - Running precondition check: Check if Proxmox host
2024-08-10 11:55:21,830 - INFO - Running precondition check: Check if GPU exists
2024-08-10 11:55:21,877 - INFO - Logging hardware information...
/bin/sh: 1: sudo: not found
2024-08-10 11:55:21,881 - ERROR - Failed to retrieve hardware information: No stderr output
2024-08-10 11:55:21,881 - ERROR - An error occurred: Hardware information retrieval failed.. Rolling back changes...
2024-08-10 11:55:21,881 - ERROR - Rollback complete. Please check the system state.
2024-08-10 11:55:21,882 - ERROR - Configuration error: Hardware information retrieval failed.
root@pmox:~/gpu-passthrough-setup# chmod 777 ./
root@pmox:~/gpu-passthrough-setup# ./main.py
2024-08-10 11:56:16,691 - INFO - Checking preconditions...
2024-08-10 11:56:16,691 - INFO - Running precondition check: Check if script is run as root
2024-08-10 11:56:16,696 - INFO - Running precondition check: Check if Proxmox host
2024-08-10 11:56:16,698 - INFO - Running precondition check: Check if GPU exists
2024-08-10 11:56:16,736 - INFO - Logging hardware information...
/bin/sh: 1: sudo: not found
2024-08-10 11:56:16,738 - ERROR - Failed to retrieve hardware information: No stderr output
2024-08-10 11:56:16,739 - ERROR - An error occurred: Hardware information retrieval failed.. Rolling back changes...
2024-08-10 11:56:16,739 - ERROR - Rollback complete. Please check the system state.
2024-08-10 11:56:16,739 - ERROR - Configuration error: Hardware information retrieval failed.`

Proxmox console defaults to root so not sure what's going on here. On proxmox 8.2.2

**Comment by keysteal72** [comment]
same error on Proxmox 8.2.2

**Comment by keysteal72** [comment]
I've modified logger.py at line 13 from logs/gpu_passthrough.log into /var/log/gpu_passthrough.log and run again main.py as sudo, and seems to work.

**Comment by AwfulCharlie** [comment]
Great idea, and gave it a try on the basis I've not made progress with other methods so far: However, as above with Proxmox 8.2.7:
./setup.py doesn't exist, ran ./main.py (after chmod +x)
FileNotFoundError: [Errno 2] No such file or directory: '/root/gpu-passthrough-setup/logs/gpu_passthrough.log'
mkdir /root/gpu-passthrough-setup/logs/
Removed 'sudo' prefix from command at line 18 in src/hardware_info.py
ERROR - An error occurred: 'GrubConfig' object has no attribute 'restore_grub_config'. Rolling back changes...
System is UEFI/systemd-boot so no grub installed.
Gave up for now at this point
